services:
  - type: web
    name: sajtstudio
    env: node
    plan: starter
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: NODE_OPTIONS
        value: --max-old-space-size=4096
      - key: NEXT_TELEMETRY_DISABLED
        value: 1
    healthCheckPath: /api/health

